import type { IProfile } from '@/models/Profile';
import type { IProject } from '@/models/Project';
import type { ISkill } from '@/models/Skill';
import type { ISettings } from '@/models/Settings';

export const fallbackProfile: IProfile = {
  _id: 'main',
  name: 'Gugulothu Akhil Kumar',
  role: 'AI & Full-Stack Engineer',
  tagline: 'ARCHITECTING PRODUCTION GENAI APPS, REAL-TIME VOICE AGENTS & ENTERPRISE RAG.',
  shortBio: 'AI & Full-Stack Engineer with 10+ months shipping production GenAI applications at Allcognix AI. Specializing in real-time voice AI (LiveKit, Whisper, WebRTC), LangGraph multi-agent systems, Model Context Protocol (MCP), and full-stack development with Python, FastAPI, TypeScript, and Next.js.',
  longBio: 'AI & Full-Stack Engineer with 10+ months of experience shipping production GenAI applications. Skilled in Large Language Model (LLM) integration, agentic systems (LangGraph, LangChain, Model Context Protocol), Retrieval-Augmented Generation (RAG), real-time voice AI and full-stack development with Python, FastAPI, TypeScript, Next.js and React. Proven record of taking AI features from prototype to scalable, production-grade deployments.',
  designPhilosophy: 'Deterministic agentic design over probabilistic randomness. We architect AI systems with sub-1.2s voice latencies, strict state machine checkpoints, human-in-the-loop controls, and zero-compromise industrial telemetry interfaces.',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
  resumeUrl: '',
  email: 'enigmasrealm77@gmail.com',
  phone: '+91 70754 00204',
  location: 'Hyderabad, India [UTC+5:30]',
  availability: 'OPEN FOR PRODUCTION GENAI ROLES & CONTRACTS',
  socials: {
    github: 'https://github.com/LaZy-Wolf',
    linkedin: 'https://www.linkedin.com/in/akhil-kumar9/',
    twitter: '',
    dribbble: '',
    behance: '',
  },
  experience: [
    {
      role: 'GenAI Full-Stack Engineer Intern',
      company: 'Allcognix AI',
      location: 'Remote (India)',
      period: 'Nov 2025 – Present',
      points: [
        'Built and shipped 4+ production AI products end-to-end across sales automation, automated software QA, financial operations and an AI-native CRM, consolidating manual multi-tool workflows into single AI-driven platforms.',
        'Deliver full-stack features that integrate LLMs into FastAPI backends and React/Next.js frontends, using PostgreSQL for persistence and Redis for caching.',
        'Design LLM-powered agentic workflows with LangGraph/LangChain that automate enterprise operations and cut manual effort.',
        'Collaborate in an agile team to take AI features from prototype to reliable, scalable production deployments.',
      ],
    },
  ],
  education: [
    {
      degree: 'B.Tech, Computer Science and Engineering (Artificial Intelligence & Machine Learning)',
      institution: 'Malla Reddy University, Hyderabad',
      period: '2022 – Jun 2026',
      cgpa: '8.6 / 10.0',
      coursework: 'Artificial Intelligence, Machine Learning, Deep Learning, Cloud Computing',
    },
  ],
  achievements: [
    '2nd Prize, National Hackathon, Malla Reddy University (GenAI chatbot)',
    'Second-Round Qualifier, Google GRID Hackathon',
    'Participant & Innovator, Bolt AI Hackathon',
  ],
  certifications: [
    'Google Cloud Computing Certification (GDSC, 2024)',
    'Programming in Java (NPTEL, 2024)',
  ],
};

export const fallbackProjects: IProject[] = [
  {
    _id: 'proj-1',
    title: 'SONAR: Real-Time Voice Agent with MCP Tool Use',
    slug: 'sonar-realtime-voice-agent',
    summary: 'Interruptible real-time voice agent built on LiveKit Agents and WebRTC with Silero VAD, semantic turn detection, Groq Whisper STT, Groq → Gemini fallback chain, and Kokoro TTS on CPU.',
    role: 'Lead AI & Systems Engineer',
    year: '2026',
    timeline: 'Active // Sep 2026 – Present',
    status: 'published',
    featured: true,
    order: 1,
    thumbnailUrl: 'https://images.unsplash.com/photo-1589254065878-42c9da997008?auto=format&fit=crop&w=1200&q=80',
    galleryUrls: [
      'https://images.unsplash.com/photo-1589254065878-42c9da997008?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    ],
    techStack: [
      'Python',
      'LiveKit Agents',
      'WebRTC',
      'Silero VAD',
      'Groq Whisper',
      'Kokoro TTS',
      'FastMCP',
      'SQLite',
      'Gemini LLM',
    ],
    tags: ['Real-Time AI', 'LiveKit', 'WebRTC', 'Voice Agent', 'FastMCP', 'Python'],
    links: {
      live: 'https://github.com/LaZy-Wolf/Sonar-Voice-Agent',
      repository: 'https://github.com/LaZy-Wolf/Sonar-Voice-Agent',
    },
    metrics: [
      { label: 'Time-to-First-Audio', value: '< 1.2s on CPU (No GPU)' },
      { label: 'Infrastructure Cost', value: '$0.00 Budget Architecture' },
      { label: 'Turn Detection', value: 'Silero VAD + Semantic Cut' },
      { label: 'LLM Fallback', value: 'Groq Llama → Gemini' },
    ],
    processSteps: [
      'LiveKit WebRTC Audio Pipeline & Room Management',
      'Dual STT Architecture: Cloud Groq Whisper with Local faster-whisper Fallback',
      'FastMCP Server Tooling: SQLite Customer Lookup & Calendar Booking',
      'End-to-End Latency Instrumentation: VAD -> STT -> TTFT -> TTS',
    ],
    caseStudyBlocks: [
      {
        id: 's1',
        type: 'heading',
        content: 'Sub-1.2s Real-Time Voice Architecture on Zero GPU Hardware',
      },
      {
        id: 's2',
        type: 'paragraph',
        content: 'Conventional voice assistants suffer from noticeable 2-4 second latency delays and awkward interruptions. SONAR was engineered as an interruptible, low-latency voice pipeline designed to run on modest hardware (standard CPU laptop without dedicated GPU) while maintaining human-grade turn-taking.',
      },
      {
        id: 's3',
        type: 'quote',
        quote: 'SONAR integrates Silero Voice Activity Detection (VAD) with semantic turn detection, allowing callers to naturally interrupt the agent mid-sentence without audio clipping or buffer lockups.',
        author: 'Silero VAD Architecture',
      },
      {
        id: 's4',
        type: 'metric',
        label: 'Measured Pipeline Latency',
        value: 'p50: 980ms | p95: 1,180ms',
      },
      {
        id: 's5',
        type: 'heading',
        content: 'MCP Protocol Tool Execution',
      },
      {
        id: 's6',
        type: 'paragraph',
        content: 'Exposing customer lookup, lead capture, and site-visit booking as agent-callable actions through a custom FastMCP server backed by SQLite. The agent reasons through caller requests and triggers external system updates with strict schema validation.',
      },
      {
        id: 's7',
        type: 'paragraph',
        content: 'FastMCP Handler: @mcp.tool() async def book_site_visit(customer_id: str, scheduled_time: str, notes: str = "") -> str: inserts confirmed records into SQLite with full audit telemetry and zero infrastructure overhead.',
      },
    ],
  },
  {
    _id: 'proj-2',
    title: 'ASOC: Agentic RAG Platform with MCP Integration',
    slug: 'asoc-agentic-rag-platform',
    summary: 'Production-grade enterprise RAG pipeline with vector-database retrieval, embeddings, semantic chunking, hybrid search (keyword + vector), reranking, and LangGraph multi-agent orchestration.',
    role: 'GenAI Architect',
    year: '2025',
    timeline: 'Production Grade',
    status: 'published',
    featured: true,
    order: 2,
    thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    galleryUrls: [
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    ],
    techStack: [
      'Python',
      'LangGraph',
      'LangChain',
      'FastAPI',
      'Vector DB',
      'FastMCP',
      'PostgreSQL',
      'Hybrid Search',
    ],
    tags: ['Agentic AI', 'RAG', 'LangGraph', 'MCP', 'Hybrid Search', 'Vector DB'],
    links: {
      live: 'https://github.com/LaZy-Wolf',
      repository: 'https://github.com/LaZy-Wolf',
    },
    metrics: [
      { label: 'Retrieval Grounding', value: '96.4% Accuracy' },
      { label: 'Search Mechanism', value: 'Hybrid (BM25 + Vector)' },
      { label: 'Agent Workflow', value: 'LangGraph State Machines' },
      { label: 'Tool Protocol', value: 'Claude-Compatible MCP' },
    ],
    processSteps: [
      'Document Parsing & Context-Aware Semantic Chunking',
      'Hybrid Vector + Keyword BM25 Ingestion & Cross-Encoder Reranking',
      'LangGraph State Machine with Checkpointing & Human-in-the-Loop Approval',
      'FastMCP Enterprise Tool Endpoints for External Action Execution',
    ],
    caseStudyBlocks: [
      {
        id: 'a1',
        type: 'heading',
        content: 'Deterministic Grounded Intelligence',
      },
      {
        id: 'a2',
        type: 'paragraph',
        content: 'Standard naive RAG implementations fail on ambiguous multi-part questions or when domain vocabulary differs from embeddings. ASOC integrates semantic chunking with hybrid keyword + vector retrieval and cross-encoder reranking to ensure that retrieved context is factually accurate and non-hallucinatory.',
      },
      {
        id: 'a3',
        type: 'metric',
        label: 'Factual Accuracy Score',
        value: '96.4% Grounded',
      },
      {
        id: 'a4',
        type: 'paragraph',
        content: 'Orchestrated using LangGraph state machines with explicit checkpointing. Risky enterprise operations require human-in-the-loop authorization before committing changes through the Claude-compatible MCP server interface.',
      },
    ],
  },
  {
    _id: 'proj-3',
    title: 'LUMINA: AI-Powered Misinformation Detection Platform',
    slug: 'lumina-misinformation-detection',
    summary: 'Multimodal misinformation detection engine built with LangGraph, LangChain, and FastAPI that analyzes text, images, video, URLs, and social feeds with 95% classification accuracy.',
    role: 'Computer Vision & NLP Lead',
    year: '2025',
    timeline: '6 Weeks',
    status: 'published',
    featured: true,
    order: 3,
    thumbnailUrl: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&w=1200&q=80',
    galleryUrls: [
      'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&w=1200&q=80',
    ],
    techStack: [
      'FastAPI',
      'LangGraph',
      'LangChain',
      'Gemini Pro Vision',
      'Groq Llama',
      'Python',
      'Redis',
      'Tailwind CSS',
    ],
    tags: ['Multimodal AI', 'Gemini Vision', 'LangGraph', 'FastAPI', 'Fact Checking', 'Python'],
    links: {
      live: 'https://github.com/LaZy-Wolf',
      repository: 'https://github.com/LaZy-Wolf',
    },
    metrics: [
      { label: 'Classification Accuracy', value: '95.0% Across Feeds' },
      { label: 'Modality Coverage', value: 'Text, Images, Videos, URLs' },
      { label: 'Batch Processing', value: 'Parallel Fact-Checking' },
      { label: 'Inference Backend', value: 'Gemini Vision + Groq' },
    ],
    processSteps: [
      'Multimodal Input Preprocessing & OCR Extraction',
      'Claim Dissection & Cross-Source Reference Search',
      'Bias Detection & Neutral Context Synthesis',
      'Provider-Agnostic Scalable Pipeline Deployment',
    ],
    caseStudyBlocks: [
      {
        id: 'l1',
        type: 'heading',
        content: 'Combatting Digital Synthetic Disinformation',
      },
      {
        id: 'l2',
        type: 'paragraph',
        content: 'LUMINA ingests controversial claims, manipulated imagery, video snippets, and social URLs. By combining Gemini Pro Vision for visual forensics and Groq Llama for semantic reasoning, it delivers automated neutral truth scoring and context summarization.',
      },
      {
        id: 'l3',
        type: 'metric',
        label: 'Multimodal Precision',
        value: '95.0% Accuracy',
      },
    ],
  },
  {
    _id: 'proj-4',
    title: 'ClearCue: AI Skincare Consultation App',
    slug: 'clearcue-ai-skincare',
    summary: 'AI-assisted clinical skincare consultation web application delivering personalized skin analysis, algorithmic treatment regimens, and downloadable PDF reports.',
    role: 'Full-Stack AI Engineer',
    year: '2024',
    timeline: '4 Weeks',
    status: 'published',
    featured: false,
    order: 4,
    thumbnailUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=80',
    galleryUrls: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=80',
    ],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Google Gemini API', 'React', 'jsPDF'],
    tags: ['Next.js 14', 'TypeScript', 'Gemini API', 'HealthTech', 'Tailwind CSS'],
    links: {
      live: 'https://github.com/LaZy-Wolf',
      repository: 'https://github.com/LaZy-Wolf',
    },
    metrics: [
      { label: 'Report Generation', value: '< 3s Automated PDF' },
      { label: 'Diagnostic Engine', value: 'Gemini Multimodal' },
      { label: 'Architecture', value: 'Next.js 14 App Router' },
    ],
    processSteps: [
      'User Diagnostic Questionnaire & Image Ingestion',
      'Gemini Vision Skin Condition Analysis',
      'Personalized Morning / Night Treatment Regimen Formulation',
      'Automated PDF Clinical Report Generation & Download',
    ],
    caseStudyBlocks: [
      {
        id: 'c1',
        type: 'heading',
        content: 'AI-Powered Dermatological Telehealth',
      },
      {
        id: 'c2',
        type: 'paragraph',
        content: 'ClearCue translates complex dermatological advice into personalized, actionable routines based on skin sensitivity, lifestyle habits, and active ingredient safety profiles.',
      },
    ],
  },
  {
    _id: 'proj-5',
    title: 'AK-9: Hands-Free Voice Assistant',
    slug: 'ak-9-voice-assistant',
    summary: 'Embedded on-device voice assistant combining custom Porcupine wake-word activation, Whisper speech recognition, and Gemini reasoning.',
    role: 'AI Systems Developer',
    year: '2024',
    timeline: '3 Weeks',
    status: 'published',
    featured: false,
    order: 5,
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    galleryUrls: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    ],
    techStack: ['Python', 'Porcupine Wake Word', 'OpenAI Whisper', 'Google Gemini', 'PyAudio'],
    tags: ['Voice AI', 'Whisper STT', 'Porcupine', 'Gemini', 'Python'],
    links: {
      live: 'https://github.com/LaZy-Wolf',
      repository: 'https://github.com/LaZy-Wolf',
    },
    metrics: [
      { label: 'Wake-Word Trigger', value: '< 120ms Local Response' },
      { label: 'Audio Filtering', value: 'Noise-Suppressed Dual Mic' },
      { label: 'Reasoning Engine', value: 'Google Gemini' },
    ],
    processSteps: [
      'Porcupine Custom Hotword Training & Continuous Audio Ring Buffer',
      'Whisper Speech-to-Text Transcription upon Wake Signal',
      'Gemini Conversational Contextual Intent Resolution',
      'Text-to-Speech Audio Feedback Dispatch',
    ],
    caseStudyBlocks: [
      {
        id: 'ak1',
        type: 'heading',
        content: 'Zero-Touch Voice Control Plane',
      },
      {
        id: 'ak2',
        type: 'paragraph',
        content: 'AK-9 operates continuously in the background using minimal CPU cycles until the Porcupine custom wake word triggers audio capture and streaming STT transcription.',
      },
    ],
  },
  {
    _id: 'proj-6',
    title: 'Serverless Email API Gateway',
    slug: 'serverless-email-api',
    summary: 'High-throughput transactional email dispatcher deployed on AWS Lambda using Serverless Framework with Next.js administration console.',
    role: 'Cloud Backend Engineer',
    year: '2024',
    timeline: '2 Weeks',
    status: 'published',
    featured: false,
    order: 6,
    thumbnailUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
    galleryUrls: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
    ],
    techStack: ['AWS Lambda', 'Serverless Framework', 'Next.js', 'Node.js', 'AWS SES'],
    tags: ['Serverless', 'AWS Lambda', 'Cloud Functions', 'Node.js', 'API'],
    links: {
      live: 'https://github.com/LaZy-Wolf',
      repository: 'https://github.com/LaZy-Wolf',
    },
    metrics: [
      { label: 'Queue Dispatch Success', value: '99.98% Deliverability' },
      { label: 'Cold Start Latency', value: '< 190ms V8 Runtime' },
      { label: 'Infrastructure Cost', value: '$0 Serverless Tier' },
    ],
    processSteps: [
      'Serverless Framework YAML Infrastructure as Code',
      'AWS Lambda Handler & AWS SES Signature Verification',
      'Rate-Limiting & Anti-Spam Middleware Validation',
      'Next.js Operator Dashboard for Delivery Logs',
    ],
    caseStudyBlocks: [
      {
        id: 'em1',
        type: 'heading',
        content: 'Scalable Cloud Dispatch Architecture',
      },
      {
        id: 'em2',
        type: 'paragraph',
        content: 'A robust transactional email infrastructure operating entirely inside AWS Lambda free tier limits, providing programmatic endpoints and real-time delivery telemetry.',
      },
    ],
  },
];

export const fallbackSkills: ISkill[] = [
  {
    _id: 'sk-1',
    category: 'AI / LLMs & Agentic Systems',
    items: [
      'LangGraph',
      'LangChain',
      'Model Context Protocol (MCP)',
      'RAG Pipelines',
      'Tool / Function Calling',
      'Prompt Engineering',
      'Multimodal AI (Gemini Vision)',
      'Vector Databases',
      'Semantic Chunking & Reranking',
    ],
    order: 1,
  },
  {
    _id: 'sk-2',
    category: 'Voice & Real-Time AI',
    items: [
      'LiveKit Agents',
      'WebRTC Audio Streams',
      'Whisper (Speech-to-Text)',
      'faster-whisper',
      'Kokoro TTS',
      'Silero VAD (Voice Activity Detection)',
      'Porcupine Wake Word',
    ],
    order: 2,
  },
  {
    _id: 'sk-3',
    category: 'Programming Languages',
    items: ['Python', 'TypeScript', 'JavaScript', 'SQL', 'HTML5', 'CSS3'],
    order: 3,
  },
  {
    _id: 'sk-4',
    category: 'Backend & Data Engineering',
    items: [
      'FastAPI',
      'Node.js',
      'Flask',
      'Django',
      'REST APIs',
      'PostgreSQL',
      'MongoDB Atlas',
      'Redis Caching',
      'SQLite',
      'Pandas & NumPy',
      'scikit-learn',
      'OpenCV',
    ],
    order: 4,
  },
  {
    _id: 'sk-5',
    category: 'Cloud, DevOps & Frontend',
    items: [
      'Next.js 15 App Router',
      'React.js',
      'Tailwind CSS',
      'AWS (Lambda, S3)',
      'Docker Containers',
      'Serverless Framework',
      'Git / GitHub CI',
      'Vercel Platform',
      'Cloudinary CDN',
    ],
    order: 5,
  },
];

export const fallbackSettings: ISettings = {
  _id: 'main',
  theme: 'dark',
  accentColor: '#E61919',
  hero: {
    headline: 'ARCHITECTING PRODUCTION GENAI APPS, REAL-TIME VOICE AGENTS & ENTERPRISE RAG.',
    subtext: 'AI & Full-Stack Engineer with 10+ months shipping production GenAI applications at Allcognix AI. Specializing in LangGraph multi-agent systems, Model Context Protocol (MCP), and sub-1.2s voice pipelines.',
    primaryCtaLabel: 'View Projects',
    secondaryCtaLabel: 'Transmit Message',
    showAvailabilityBadge: true,
  },
  sections: [
    { id: 'hero', label: 'Hero', visible: true, order: 1 },
    { id: 'featured-projects', label: 'Featured Projects', visible: true, order: 2 },
    { id: 'projects', label: 'All Projects', visible: true, order: 3 },
    { id: 'about', label: 'About & Career', visible: true, order: 4 },
    { id: 'skills', label: 'Arsenal', visible: true, order: 5 },
    { id: 'contact', label: 'Transmission', visible: true, order: 6 },
  ],
  footer: {
    text: 'TELEMETRY ACTIVE // GUGULOTHU AKHIL KUMAR // HYDERABAD, INDIA',
    showAdminLink: true,
  },
  ai: {
    enabled: true,
    greeting: 'Telemetry online. I am the Digital Twin of Gugulothu Akhil Kumar. Ask me about my production GenAI products at Allcognix AI, real-time voice systems, LangGraph, MCP, or my stack.',
    fallbackMessage: 'AI Digital Twin telemetry offline. Please review case studies below or reach out directly at enigmasrealm77@gmail.com.',
    provider: 'groq',
  },
  seo: {
    title: 'Gugulothu Akhil Kumar // AI & Full-Stack Engineer',
    description: 'Portfolio of Gugulothu Akhil Kumar &mdash; AI & Full-Stack Engineer specializing in GenAI, LangGraph, Model Context Protocol (MCP), Real-Time Voice Agents, and Full-Stack Engineering.',
    ogImageUrl: 'https://images.unsplash.com/photo-1589254065878-42c9da997008?auto=format&fit=crop&w=1200&q=80',
  },
};
